<a href="https://colab.research.google.com/github/arnavbhatiamait/model-landmark-detection/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project on Landmark Detection

In [1]:
! pip install kaggle

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
! mkdir ~/.kaggle


In [4]:
#! cp kaggle.json ~/.kaggle/

In [5]:
!cp /content/drive/MyDrive/kaggle.json ~/.kaggle/kaggle.json

In [6]:
! chmod 600 ~/.kaggle/kaggle.json


In [7]:
! kaggle datasets download -d danushkumarv/indian-monuments-image-dataset

 97% 601M/621M [00:11<00:00, 104MB/s] 
100% 621M/621M [00:11<00:00, 56.6MB/s]


In [8]:

! unzip /content/indian-monuments-image-dataset.zip

Archive:  /content/indian-monuments-image-dataset.zip
  inflating: Indian-monuments/images/test/Ajanta Caves/1.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/10.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/11.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/12.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/13.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/14.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/15.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/16.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/17.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/18.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/19.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/2.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/20.jpg  
  inflating: Indian-monuments/images/test/Ajanta Caves/21.jpg  
  inflating: Indian-monuments/images/test/Ajanta Cav

Importing libraries

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

Preprocessing the test data set

In [10]:
train_data_generator=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
training_test=train_data_generator.flow_from_directory("/content/Indian-monuments/images/train",target_size=(256,256),batch_size=32,class_mode="categorical")

Found 3666 images belonging to 24 classes.


Preprocessing the test data set

In [11]:
test_data_generator=ImageDataGenerator(rescale=1./255)
testing_set=test_data_generator.flow_from_directory("/content/Indian-monuments/images/test",target_size=(256,256),batch_size=32,class_mode='categorical')

Found 1049 images belonging to 24 classes.


Buliding CNN initialization

In [12]:
cnn=tf.keras.models.Sequential()

1sr layer

In [13]:
cnn.add(tf.keras.layers.Conv2D(filters=256,kernel_size=3,activation="relu",input_shape=[256,256,3]))

pooling

In [14]:
# max pooling
cnn.add(tf.keras.layers.MaxPool2D(strides=2,pool_size=2))

2nd convolutional layer

In [15]:
cnn.add(tf.keras.layers.Conv2D(filters=256,kernel_size=3,activation="relu"))
cnn.add(tf.keras.layers.MaxPool2D(strides=2,pool_size=2))

Flattening

In [16]:
cnn.add(tf.keras.layers.Flatten())

Full connectes layer

In [17]:
cnn.add(tf.keras.layers.Dense(activation="relu",units=128))

Output layer

In [18]:
cnn.add(tf.keras.layers.Dense(activation="softmax",units=24))

Compiling the cnn model

In [19]:
cnn.compile(optimizer="adam", loss="categorical_crossentropy", metrics=['accuracy'])

training the model

In [20]:
cnn.fit(x=training_test,validation_data=testing_set,epochs=100)

Epoch 1/100
115/115 [==============================] - 131s 984ms/step - loss: 3.7558 - accuracy: 0.1729 - val_loss: 3.3790 - val_accuracy: 0.1868
Epoch 2/100
115/115 [==============================] - 102s 884ms/step - loss: 2.3792 - accuracy: 0.3055 - val_loss: 3.1343 - val_accuracy: 0.1792
Epoch 3/100
115/115 [==============================] - 104s 896ms/step - loss: 2.0954 - accuracy: 0.3985 - val_loss: 3.0419 - val_accuracy: 0.2269
Epoch 4/100
115/115 [==============================] - 106s 915ms/step - loss: 1.8807 - accuracy: 0.4588 - val_loss: 3.3478 - val_accuracy: 0.2421
Epoch 5/100
115/115 [==============================] - 104s 907ms/step - loss: 1.6883 - accuracy: 0.5087 - val_loss: 3.3955 - val_accuracy: 0.3127
Epoch 6/100
115/115 [==============================] - 103s 890ms/step - loss: 1.5496 - accuracy: 0.5456 - val_loss: 3.4306 - val_accuracy: 0.2936
Epoch 7/100
115/115 [==============================] - 104s 898ms/step - loss: 1.4484 - accuracy: 0.5638 - val_loss: 3

In [22]:
training_test.class_indices

{'Ajanta Caves': 0,
 'Charar-E- Sharif': 1,
 'Chhota_Imambara': 2,
 'Ellora Caves': 3,
 'Fatehpur Sikri': 4,
 'Gateway of India': 5,
 'Humayun_s Tomb': 6,
 'India gate pics': 7,
 'Khajuraho': 8,
 'Sun Temple Konark': 9,
 'alai_darwaza': 10,
 'alai_minar': 11,
 'basilica_of_bom_jesus': 12,
 'charminar': 13,
 'golden temple': 14,
 'hawa mahal pics': 15,
 'iron_pillar': 16,
 'jamali_kamali_tomb': 17,
 'lotus_temple': 18,
 'mysore_palace': 19,
 'qutub_minar': 20,
 'tajmahal': 21,
 'tanjavur temple': 22,
 'victoria memorial': 23}

predicting a result

In [26]:
from tensorflow.keras.preprocessing import image
test_img=image.load_img("/content/Indian-monuments/images/test/Ajanta Caves/4.jpg",target_size=(64,64))
test_img=image.img_to_array(test_img)
test_img=np.expand_dims(test_img,axis=0)
# making the right format
result=cnn.predict(test_img)
training_test.class_indices
print(result)
# if result[0][0]==1:
#     prediction="Dog"
# else:
#     prediction="Cat"

ValueError: in user code:

    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 2440, in predict_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 2425, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 2413, in run_step  **
        outputs = model.predict_step(data)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 2381, in predict_step
        return self(x, training=False)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 256, 256, 3), found shape=(None, 64, 64, 3)


In [33]:
def result_of_the_model(path):
    test_img=image.load_img(path,target_size=(256,256))
    test_img=image.img_to_array(test_img)
    test_img=np.expand_dims(test_img,axis=0)
    # making the right format
    result=cnn.predict(test_img)
    training_test.class_indices
    print(result)

In [34]:
result_of_the_model("/content/Indian-monuments/images/train/charminar/(3).jpg")
result_of_the_model("/content/Indian-monuments/images/test/Charar-E- Sharif/51.jpg")
result_of_the_model("/content/Indian-monuments/images/test/Sun Temple Konark/5.jpg")
result_of_the_model("/content/Indian-monuments/images/train/qutub_minar/img9.jpg")
result_of_the_model("/content/Indian-monuments/images/test/victoria memorial/174.jpg")
result_of_the_model("/content/Indian-monuments/images/test/tajmahal/86.jpg")
result_of_the_model("/content/Indian-monuments/images/test/mysore_palace/8.jpg")

1/1 [==============================] - 0s 18ms/step
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 17ms/step
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 1.1200959e-31 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]]
1/1 [==============================] - 0s 16ms/step
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 20ms/step
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
1/1 [==============================] - 0s 26ms/step
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0

In [35]:
result_of_the_model("/content/Indian-monuments/images/test/Ellora Caves/7.jpg")

1/1 [==============================] - 0s 18ms/step
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [32]:
def result_of_the_model2(path):
    test_img=image.load_img(path,target_size=(256,256))
    test_img=image.img_to_array(test_img)
    test_img=np.expand_dims(test_img,axis=0)
    # making the right format
    result=cnn.predict(test_img)
    training_test.class_indices
    print(result)
    return result

In [31]:
m=0
for i in range(1,31):
    # Ajanta caves
    pat="/content/Indian-monuments/images/test/basilica_of_bom_jesus/"+str(i)+".jpg"
    a=result_of_the_model2(pat)
    if( a[0][12]==1):
        m+=1
        print("Ajanta Caves")
print(m)

1/1 [==============================] - 0s 18ms/step
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Ajanta Caves
1/1 [==============================] - 0s 17ms/step
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 17ms/step
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 1.0000000e+00 3.7558234e-29 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]]
Ajanta Caves
1/1 [==============================] - 0s 18ms/step
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Ajanta Caves
1/1 [==============================] - 0s 18ms/step
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 18ms/st

In [27]:
cnn.save("model.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [28]:
import keras
keras.saving.save_model(cnn, 'my_model10.keras')